import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} antialiased scroll-smooth lg:h-dvh h-full`}
      >
        <img src={"/assets/loch-one-bg.png"} alt="bg" className="w-full h-full fixed -z-1" />
        {children}
      </body>
    </html>
  );
}
